### ISSUE TITLE
Alwasy get urllib2.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by hsluoyz** [ox-it/python-sharepoint#35]
Hi. This is how I use the code. And I always get the 403 error. In the web browser, I always use the email account to login. I don't know the username here is the Email address I used to login the www.office.com website? The username I used is ``xxx@pku.edu.cn``. Is this right? Or I should use some translated names like ``pku_edu_cn\\xxx``?

```python
from sharepoint import SharePointSite, basic_auth_opener

server_url = "https://pkueducn-my.sharepoint.com/"
site_url = server_url + "personal/xxx_pku_edu_cn"

opener = basic_auth_opener(server_url, "xxx@pku.edu.cn", "my_password")

site = SharePointSite(site_url, opener)

for sp_list in site.lists:
    print sp_list.id, sp_list.meta['Title']
```

My error:
```
C:\Python27\python.exe J:/github_repos/xxx/sp.py
Traceback (most recent call last):
  File "J:/github_repos/xxx/sp.py", line 17, in <module>
    for sp_list in site.lists:
  File "C:\Python27\lib\site-packages\sharepoint\lists\__init__.py", line 80, in __iter__
    return iter(self.all_lists)
  File "C:\Python27\lib\site-packages\sharepoint\lists\__init__.py", line 36, in all_lists
    result = self.opener.post_soap(LIST_WEBSERVICE, xml)
  File "C:\Python27\lib\site-packages\sharepoint\site.py", line 32, in post_soap
    response = self.opener.open(request, timeout=self.timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

Process finished with exit code 1

```

**Comment by esamtian** [comment]
I have same issue when I use this model to visit my SharePoint site, who can support this?

**Comment by b0207191** [comment]
well ,my question is 
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized

**Comment by DuiduiLi** [comment]
Hi,
My suggestion is, the username is the email address, the password is not the computer/email password, it should be the app password. So please create your app follow the guide in https://docs.microsoft.com/zh-cn/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords
